### ISSUE TITLE
Error: Cannot find module 'resolve'

### ISSUE THREAD

**Issue by richb-hanover** [MattMcFarland/reactathon#27]
I got the following error on OSX 10.10.5, checking out 392a5ef of 25Jan2016. 

1) I cloned the repo, and entered `npm install && npm run dev` . I got the output in http://pastebin.com/fQ9Avsb1

2) I re-ran `npm install && npm run dev` and got the following.

Any thoughts about what I can do to fix this? Thanks!

```
bash-3.2$ npm install && npm run dev

> reactathon@0.0.1 postinstall /Users/richb/github/reactathon
> npm run build


> reactathon@0.0.1 build /Users/richb/github/reactathon
> rm -rf lib/* && babel server/src --ignore __tests__ --out-dir lib && gulp build && npm run copy

server/src/app.config.js -> lib/app.config.js
server/src/app.js -> lib/app.js
server/src/auth/index.js -> lib/auth/index.js
server/src/auth/modules.js -> lib/auth/modules.js
server/src/auth/passport.js -> lib/auth/passport.js
server/src/bin/modules.js -> lib/bin/modules.js
server/src/bin/server.js -> lib/bin/server.js
server/src/database/index.js -> lib/database/index.js
server/src/database/models/Article.js -> lib/database/models/Article.js
server/src/database/models/Comment.js -> lib/database/models/Comment.js
server/src/database/models/Flag.js -> lib/database/models/Flag.js
server/src/database/models/Tag.js -> lib/database/models/Tag.js
server/src/database/models/TagItem.js -> lib/database/models/TagItem.js
server/src/database/models/Token.js -> lib/database/models/Token.js
server/src/database/models/User.js -> lib/database/models/User.js
server/src/database/models/Vote.js -> lib/database/models/Vote.js
server/src/database/models/customTypes/URL.js -> lib/database/models/customTypes/URL.js
server/src/database/models/customTypes/email.js -> lib/database/models/customTypes/email.js
server/src/database/models/customTypes/index.js -> lib/database/models/customTypes/index.js
server/src/database/models/index.js -> lib/database/models/index.js
server/src/database/modules.js -> lib/database/modules.js
server/src/modules.js -> lib/modules.js
server/src/routes/api.js -> lib/routes/api.js
server/src/routes/auth.js -> lib/routes/auth.js
server/src/routes/index.js -> lib/routes/index.js
server/src/routes/modules.js -> lib/routes/modules.js
server/src/routes/root.js -> lib/routes/root.js
server/src/schema/index.js -> lib/schema/index.js
server/src/utils/fromGravatar.js -> lib/utils/fromGravatar.js
server/src/utils/getGravatar.js -> lib/utils/getGravatar.js
server/src/utils/index.js -> lib/utils/index.js
server/src/utils/logger.js -> lib/utils/logger.js
server/src/utils/modules.js -> lib/utils/modules.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'resolve'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/richb/github/reactathon/tasks/bundledeps.js:10:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! reactathon@0.0.1 build: `rm -rf lib/* && babel server/src --ignore __tests__ --out-dir lib && gulp build && npm run copy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactathon@0.0.1 build script 'rm -rf lib/* && babel server/src --ignore __tests__ --out-dir lib && gulp build && npm run copy'.
npm ERR! This is most likely a problem with the reactathon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf lib/* && babel server/src --ignore __tests__ --out-dir lib && gulp build && npm run copy
npm ERR! You can get their info via:
npm ERR!     npm owner ls reactathon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/richb/github/reactathon/npm-debug.log

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! reactathon@0.0.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactathon@0.0.1 postinstall script 'npm run build'.
npm ERR! This is most likely a problem with the reactathon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls reactathon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/richb/github/reactathon/npm-debug.log
bash-3.2$
```

**Comment by MattMcFarland** [comment]
Strange!  I investigated and noticed that we are using module called `resolve` for one of the gulp tasks, and it is not in `dependencies` - not sure how this wasn't caught earlier.  Anyway, you should be fine with `npm install resolve` - I am going to add it to deps shortly, test and update the package soon,

**Comment by richb-hanover** [comment]
Bingo! I discarded the repo, re-cloned (and you already updated the repo to include resolve as a dependency), and it worked as expected.

NB I also upgraded to node 5.3.0 as was called out in requirements (not the 4.2.2 I had been using) so this certainly helped. (Would it make sense to display a warning if node < 5.3.0?)

I'm content - you can close the ticket.

**Comment by MattMcFarland** [comment]
Thanks, I'll add a todo to set the version for 5.3.0
