### ISSUE TITLE
Error after "npm run seed" and "npm run dev"

### ISSUE THREAD

**Issue by pihomeserver** [MattMcFarland/reactathon#36]
Hi,
I tried to use the automatic seed and get the following error :

```
[stdin]:1
babel-relay-plugin-loader: using schema at [/Users/xxx/Development/tmp/reactathon/data/schema.json]
                         ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:556:32)
    at bootstrap_node.js:357:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/nvm/0.32.0/versions/node/v6.7.0/bin/node" "/usr/local/opt/nvm/versions/node/v6.7.0/bin/npm" "run" "dev"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! reactathon@0.0.1 dev: `npm run build && babel scripts/server.js | node`
npm ERR! Exit status 1
```

Both Articles and Users tables are fed but not others

**Comment by pihomeserver** [comment]
Same error when starting the dev server

**Comment by pihomeserver** [comment]
Ok problem solved partially by removing two plugins (as described in #31 )

```
npm uninstall -g babel-relay-plugin
npm uninstall -g babel-relay-plugin-loader
```

then running a rebuild

```
npm rebuild
```

But now i got the error when running the `npm run dev`

Same issue with node v5.3.0 and v6.7.0

**Comment by 0x62** [comment]
I can reproduce this with a clean pull from the repo

**Comment by agsdot** [comment]
Experiencing the same issue as @pihomeserver and @0x62, any updates on this?

**Comment by dankirkpatrick** [comment]
I just did a clean pull from the repo and got this error as well.

I tried to uninstall the global versions of babel-relay-plugin and babel-relay-plugin-loader, as per pihomeserver, with no luck.

Any updates?

**Comment by MattMcFarland** [comment]
Hi guys, it seems to be outdated dependencies, either direct, transient, or both.  Definitely is a bug and unfortunate that it is happening!!  I suspect we'll have to change how we interface with a dependency that has changed, I'll look into it.

**Comment by agsdot** [comment]
@MattMcFarland thanks for the update!

**Comment by mikeghen** [comment]
😞 I just ran into this @MattMcFarland. Total 🚫
